# Generated by Django 3.1.14 on 2022-02-01 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220201_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Круглый ноль такой хорошенький, Но не значит ничегошеньки!')], verbose_name='время приготовления (мин)'),
        ),
    ]
