# Generated by Django 3.1.14 on 2022-01-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220127_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['follower']},
        ),
    ]
